import type { NextPage } from 'next';
import Head from 'next/head';

import styled from '@emotion/styled';
import UserInput from '../components/UserInput';

const Container = styled.div`
  width: 100vw;
  height: 100vh;
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Load Profile Modulation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/chart_graph.png' />
        {/* <link rel='icon' href='/Bar-chart.png' /> */}
      </Head>
      <UserInput />
    </Container>
  );
};

export default Home;
